Vagrant.configure(2) do |config|
 config.ssh.forward_agent = true
 
  config.vm.define "app1" do |app1|
    app1.vm.box = "bento/ubuntu-24.04"
    app1.vm.host_name = "app-server1"
    app1.vm.network "private_network", ip: "192.168.56.10"
  end
  
  config.vm.define "app2" do |app2|    
    app2.vm.box = "bento/ubuntu-24.04"
    app2.vm.host_name = "app-server2"
    app2.vm.network :private_network, ip: "192.168.56.11" 
  end  

  config.vm.define "lb" do |lb|    
    lb.vm.box = "bento/ubuntu-24.04"
    lb.vm.host_name = "load-balancer"
    lb.vm.network :private_network, ip: "192.168.56.12" 
  end
  
  config.vm.define "postgresql" do |postgres|    
    postgres.vm.box = "bento/ubuntu-24.04"
    postgres.vm.host_name = "postgres-server"
    postgres.vm.network :private_network, ip: "192.168.56.13" 
  end
 
  config.vm.define "consul" do |consul|    
    consul.vm.box = "bento/ubuntu-24.04"
    consul.vm.host_name = "consul-server"
    consul.vm.network :private_network, ip: "192.168.56.14" 
  end

end